"""Run a closed round from raw external-AI chat responses.

This module keeps chat-only participants on the same deterministic path as
file-based participants: preserve raw text, inspect the one-JSON contract,
write only accepted move JSON, judge the round, and generate the next pack.
"""

from __future__ import annotations

import argparse
import json
import shlex
import shutil
from pathlib import Path
from typing import Any

from .arena_gate import iter_quarantine_jsonl
from .chat_response import can_write_extracted_move, inspect_chat_response, write_extracted_move
from .closed_match import ClosedMatchResult, run_closed_match, write_closed_match_outputs
from .closed_test_audit import audit_records, render_audit_markdown
from .external_round_audit import audit_external_round, render_external_round_audit_markdown
from .match_pack import STRATEGY_CARDS, build_match_pack
from .season_catalog import load_optional_compiled_season


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _safe_filename(value: str) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch in {"-", "_", "."} else "_" for ch in value).strip("._-")
    return (cleaned or "item")[:80]


def _response_files(response_dir: str | Path, *, pattern: str) -> list[Path]:
    root = Path(response_dir)
    if not root.exists():
        raise FileNotFoundError(f"raw response directory does not exist: {root}")
    if not root.is_dir():
        raise NotADirectoryError(f"raw response path is not a directory: {root}")
    files = sorted(path for path in root.glob(pattern) if path.is_file())
    if not files:
        raise FileNotFoundError(f"no raw response files matched {pattern!r} in {root}")
    return files


def _participant_player(spec: str) -> str:
    raw = spec.strip()
    if "=" in raw:
        player, strategy = raw.rsplit("=", 1)
        if player.strip() and strategy.strip() in STRATEGY_CARDS:
            return player.strip()
    if ":" in raw:
        player, strategy = raw.rsplit(":", 1)
        if player.strip() and strategy.strip() in STRATEGY_CARDS:
            return player.strip()
    return raw


def _participant_strategy(spec: str) -> str:
    raw = spec.strip()
    for separator in ("=", ":"):
        if separator in raw:
            _player, strategy = raw.rsplit(separator, 1)
            if strategy.strip() in STRATEGY_CARDS:
                return strategy.strip()
    return ""


def _participant_player_map(participants: list[str] | None) -> dict[str, str]:
    mapping: dict[str, str] = {}
    for spec in participants or []:
        player = _participant_player(spec)
        if not player:
            continue
        mapping[player] = player
        mapping[_safe_filename(player)] = player
    return mapping


def _participant_roster_entries(
    participants: list[str] | None,
    intake: list[dict[str, Any]],
    *,
    roster: list[dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    reports_by_player = {
        str(item["expected_player"]): str(item["report"])
        for item in intake
        if str(item.get("expected_player", "")).strip()
    }
    raw_by_player = {
        str(item["expected_player"]): str(item["raw_copy"])
        for item in intake
        if str(item.get("expected_player", "")).strip()
    }
    roster_by_player = {str(entry.get("player", "")).strip(): dict(entry) for entry in roster or []}

    entries: list[dict[str, Any]] = []
    if participants:
        for spec in participants:
            player = _participant_player(spec)
            if not player:
                continue
            entry = roster_by_player.get(player, {"player": player})
            entry["player"] = player
            entry.setdefault("external", True)
            entry.setdefault("kind", "llm_agent")
            entry.setdefault("model", "")
            entry.setdefault("model_name", "")
            entry.setdefault("model_family", "")
            entry.setdefault("interface", "")
            entry["strategy"] = _participant_strategy(spec) or str(entry.get("strategy", ""))
            entry["raw_response"] = raw_by_player.get(player, str(entry.get("raw_response", "")))
            entry["response_report"] = reports_by_player.get(player, str(entry.get("response_report", "")))
            entry.setdefault(
                "notes",
                "Operator-supplied roster evidence generated by raw-round. Fill model/interface before final evidence if known.",
            )
            entries.append(
                entry
            )
        return entries

    for item in intake:
        player = str(item.get("expected_player", "")).strip()
        if not player:
            continue
        entry = roster_by_player.get(player, {"player": player})
        entry["player"] = player
        entry.setdefault("external", True)
        entry.setdefault("kind", "llm_agent")
        entry.setdefault("model", "")
        entry.setdefault("model_name", "")
        entry.setdefault("model_family", "")
        entry.setdefault("interface", "")
        entry.setdefault("strategy", "")
        entry["raw_response"] = str(item.get("raw_copy", "") or entry.get("raw_response", ""))
        entry["response_report"] = str(item.get("report", "") or entry.get("response_report", ""))
        entry.setdefault(
            "notes",
            "Inferred from raw response filename by raw-round. Fill model/interface before final evidence if known.",
        )
        entries.append(
            entry
        )
    return entries


def _load_participant_roster(path: str | Path | None) -> list[dict[str, Any]]:
    if path is None:
        return []
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    participants = payload.get("participants") if isinstance(payload, dict) else payload
    if not isinstance(participants, list):
        raise ValueError("participant roster must be a list or an object with a participants list")
    roster: list[dict[str, Any]] = []
    for index, item in enumerate(participants, start=1):
        if not isinstance(item, dict):
            raise ValueError(f"participant roster entry {index} must be an object")
        player = str(item.get("player", "")).strip()
        if not player:
            raise ValueError(f"participant roster entry {index} is missing player")
        roster.append(dict(item, player=player))
    return roster


def _expected_player_for_response(path: Path, participant_map: dict[str, str]) -> str:
    stem = path.stem
    return participant_map.get(stem) or participant_map.get(_safe_filename(stem)) or stem


def _copy_raw_response(source: Path, raw_out_dir: Path) -> Path:
    raw_out_dir.mkdir(parents=True, exist_ok=True)
    target = raw_out_dir / source.name
    if source.resolve() != target.resolve():
        shutil.copyfile(source, target)
    return target


def _players_from_intake(intake: list[dict[str, Any]]) -> list[str]:
    players: list[str] = []
    seen: set[str] = set()
    for item in intake:
        player = str(item.get("expected_player") or item.get("player") or "").strip()
        if player and player not in seen:
            players.append(player)
            seen.add(player)
    return players


def _evidence_command(
    *,
    canonical_path: str,
    evidence_out: Path,
    participant_roster: Path,
    response_report_dir: Path,
    round_audit: Path,
    season_path: str | Path | None,
) -> str:
    command = [
        "python",
        "-m",
        "conjecture_golf.season0",
        "evidence",
        canonical_path,
        "--out",
        str(evidence_out),
    ]
    if season_path:
        command.extend(["--season", str(season_path)])
    command.extend(
        [
            "--participant-roster",
            str(participant_roster),
            "--response-report-dir",
            str(response_report_dir),
            "--round-audit",
            str(round_audit),
            "--final-external-evidence",
        ]
    )
    return " ".join(shlex.quote(part) for part in command)


def _render_external_round_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# External AI Round Summary",
        "",
        f"Raw responses: `{summary['raw_responses']}`",
        f"Moves written: `{summary['moves_written']}`",
        f"Accepted moves: `{summary['accepted']}`",
        f"Rejected/quarantined moves: `{summary['rejected']}`",
        f"Next match pack: `{summary['next_match_pack']}`",
        "",
        "## Response Intake",
        "",
        "| response | expected player | status | contract ok | wrote move |",
        "| --- | --- | --- | ---: | ---: |",
    ]
    for item in summary["response_intake"]:
        lines.append(
            "| "
            f"`{item['response_file']}` | "
            f"`{item['expected_player']}` | "
            f"`{item['status']}` | "
            f"{str(item['contract_ok']).lower()} | "
            f"{str(item['wrote_move']).lower()} |"
        )
    lines.extend(
        [
            "",
            "## Round",
            "",
            f"- Canonical transcript: `{summary['outputs']['canonical']}`",
            f"- Quarantine transcript: `{summary['outputs']['quarantine']}`",
            f"- Participant roster: `{summary['participant_roster_template']}`",
            f"- Response reports: `{summary['response_report_dir']}`",
            f"- External round audit: `{summary['external_round_audit']}`",
            f"- Closed-test audit passed: `{str(summary['closed_test_audit']['passed']).lower()}`",
            "",
            "## Evidence Handoff",
            "",
            "Before running this as final evidence, fill `model`, `model_name`, or "
            "`model_family` plus interface notes in `participant_roster_template.json`.",
            "",
            "```bash",
            summary["evidence_command"],
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def run_external_round(
    transcript_path: str | Path,
    raw_response_dir: str | Path,
    out_dir: str | Path,
    *,
    pattern: str = "*.txt",
    participants: list[str] | None = None,
    participant_roster: str | Path | None = None,
    allow_extraction: bool = False,
    prior_quarantine: str | Path | None = None,
    min_player_interval_seconds: int = 0,
    invalid_strikes_to_disqualify: int = 3,
    move_cap: int = 24,
    reveal_policy: str = "redacted",
    season_path: str | Path | None = None,
) -> dict[str, Any]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    raw_out = out / "raw_responses"
    reports_out = out / "response_reports"
    moves_out = out / "moves"
    reports_out.mkdir(exist_ok=True)
    moves_out.mkdir(exist_ok=True)

    roster = _load_participant_roster(participant_roster)
    participant_map = _participant_player_map(participants)
    intake: list[dict[str, Any]] = []
    move_players_seen: set[str] = set()

    for response_path in _response_files(raw_response_dir, pattern=pattern):
        raw_copy = _copy_raw_response(response_path, raw_out)
        expected_player = _expected_player_for_response(response_path, participant_map)
        report = inspect_chat_response(response_path.read_text(encoding="utf-8"), expected_player=expected_player)
        report_name = f"{_safe_filename(response_path.stem)}.report.json"
        report_path = reports_out / report_name
        _write_json(report_path, report)

        payload = report.get("extracted")
        can_write = can_write_extracted_move(report, allow_extraction=allow_extraction)
        player = str(report.get("player") or expected_player)
        safe_player = _safe_filename(player)
        duplicate_player_response = safe_player in move_players_seen
        move_path: Path | None = None
        if can_write and not duplicate_player_response and isinstance(payload, dict):
            move_path = moves_out / f"{safe_player}.json"
            write_extracted_move(move_path, payload)
            move_players_seen.add(safe_player)

        intake.append(
            {
                "response_file": str(response_path),
                "raw_copy": str(raw_copy),
                "report": str(report_path),
                "expected_player": expected_player,
                "player": report.get("player"),
                "status": report["status"],
                "violations": report.get("violations", []),
                "contract_ok": report["contract_ok"],
                "allow_extraction": allow_extraction,
                "duplicate_player_response": duplicate_player_response,
                "wrote_move": move_path is not None,
                "move": str(move_path) if move_path else None,
            }
        )

    season = load_optional_compiled_season(season_path)
    prior_quarantine_records = iter_quarantine_jsonl(prior_quarantine) if prior_quarantine else None
    result: ClosedMatchResult = run_closed_match(
        transcript_path,
        moves_out,
        prior_quarantine_records=prior_quarantine_records,
        min_player_interval_seconds=min_player_interval_seconds,
        season_scoring=True,
        season=season,
        invalid_strikes_to_disqualify=invalid_strikes_to_disqualify,
    )
    outputs = write_closed_match_outputs(
        result,
        out,
        min_player_interval_seconds=min_player_interval_seconds,
        season_scoring=True,
        season=season,
        reveal_policy=reveal_policy,
    )
    audit = audit_records(
        result.canonical_records,
        season=season,
        move_cap=move_cap,
    )
    (out / "closed_test_audit.md").write_text(render_audit_markdown(audit), encoding="utf-8")
    _write_json(out / "closed_test_audit.json", audit.to_dict())

    participant_roster_path = out / "participant_roster_template.json"
    _write_json(
        participant_roster_path,
        {
            "schema": "conjecture_golf.participant_roster.v1",
            "participants": _participant_roster_entries(participants, intake, roster=roster),
        },
    )

    next_participants = participants or _players_from_intake(intake)
    next_pack = out / "next_match_pack"
    build_match_pack(
        outputs["canonical"],
        next_pack,
        min_player_interval_seconds=min_player_interval_seconds,
        reveal_policy=reveal_policy,
        season_path=season_path,
        participants=next_participants,
    )

    summary = {
        "raw_responses": len(intake),
        "moves_written": sum(1 for item in intake if item["wrote_move"]),
        "accepted": result.accepted_count,
        "rejected": result.rejected_count,
        "allow_extraction": allow_extraction,
        "participants": next_participants,
        "moves_dir": str(moves_out),
        "raw_response_dir": str(raw_out),
        "response_report_dir": str(reports_out),
        "participant_roster_template": str(participant_roster_path),
        "participant_roster_source": str(participant_roster) if participant_roster else None,
        "external_round_audit": str(out / "external_round_audit.json"),
        "evidence_command": _evidence_command(
            canonical_path=outputs["canonical"],
            evidence_out=out / "evidence",
            participant_roster=participant_roster_path,
            response_report_dir=reports_out,
            round_audit=out / "external_round_audit.json",
            season_path=season_path,
        ),
        "response_intake": intake,
        "outputs": outputs,
        "closed_test_audit": audit.to_dict(),
        "next_match_pack": str(next_pack),
        "note": (
            "This command preserves raw chat responses and uses deterministic inspection before "
            "writing move JSON. It does not prove which remote model produced a response."
        ),
    }
    _write_json(out / "external_round_summary.json", summary)
    (out / "external_round_summary.md").write_text(_render_external_round_markdown(summary), encoding="utf-8")
    round_audit = audit_external_round(out)
    _write_json(out / "external_round_audit.json", round_audit.to_dict())
    (out / "external_round_audit.md").write_text(render_external_round_audit_markdown(round_audit), encoding="utf-8")
    return summary


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Judge a closed round from raw external-AI chat responses.")
    parser.add_argument("transcript", help="Starting canonical transcript JSONL")
    parser.add_argument("raw_response_dir", help="Directory containing raw participant response text files")
    parser.add_argument("--out", required=True, help="Output round directory")
    parser.add_argument("--pattern", default="*.txt", help="Raw response file glob within raw_response_dir")
    parser.add_argument(
        "--participant",
        action="append",
        dest="participants",
        help="Participant player name or name=strategy for expected-player checks and next pack. May be repeated.",
    )
    parser.add_argument(
        "--participant-roster",
        help="Optional roster JSON to preserve model/interface evidence in the generated evidence handoff.",
    )
    parser.add_argument(
        "--allow-extraction",
        action="store_true",
        help="Allow a single JSON object to be salvaged from prose or Markdown contract violations.",
    )
    parser.add_argument("--prior-quarantine", help="Existing quarantine JSONL to carry invalid strikes forward")
    parser.add_argument("--min-player-interval-seconds", type=int, default=0)
    parser.add_argument("--invalid-strikes-to-disqualify", type=int, default=3)
    parser.add_argument("--move-cap", type=int, default=24)
    parser.add_argument("--reveal-policy", choices=["full", "redacted"], default="redacted")
    parser.add_argument("--season", help="Optional data-only season spec path")
    parser.add_argument(
        "--strict-exit",
        action="store_true",
        help="Return non-zero when any raw response fails intake or any written move is rejected.",
    )
    args = parser.parse_args(argv)
    summary = run_external_round(
        args.transcript,
        args.raw_response_dir,
        args.out,
        pattern=args.pattern,
        participants=args.participants,
        participant_roster=args.participant_roster,
        allow_extraction=args.allow_extraction,
        prior_quarantine=args.prior_quarantine,
        min_player_interval_seconds=args.min_player_interval_seconds,
        invalid_strikes_to_disqualify=args.invalid_strikes_to_disqualify,
        move_cap=args.move_cap,
        reveal_policy=args.reveal_policy,
        season_path=args.season,
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
    failed_intake = any(not item["wrote_move"] for item in summary["response_intake"])
    if args.strict_exit and (failed_intake or summary["rejected"]):
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
